#!/bin/bash
# Git Filter-Repo Path Removal Script
# This script removes files containing leaks from git history
# Generated by leak_remover.py

echo "Files to be removed from git history:"
echo "  - .specstory/history/2025-10-19_07-54Z-guest-play-mode-without-progress-saving.md"

echo ""
echo "This will rewrite git history! Make sure you have backups!"
echo "Press Ctrl+C to cancel, or Enter to continue..."
read

# Build the git filter-repo command
cmd="git filter-repo --invert-paths"
cmd="$cmd --path .specstory/history/2025-10-19_07-54Z-guest-play-mode-without-progress-saving.md"

echo "Running: $cmd"
eval $cmd

if [ $? -eq 0 ]; then
    echo "Success! Files containing leaks have been removed from git history."
    echo "You can now push the cleaned history to your remote repository."
else
    echo "Error: git filter-repo failed"
    exit 1
fi
